### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by honzaves** [spring-guides/gs-consuming-rest-backbone#1]
Hi there,

Thanks for the example, however, when used "as is", it does not work because of cross domain problems.

XMLHttpRequest cannot load http://rest-service.guides.spring.io/greeting?name=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
XHR failed loading: GET "http://rest-service.guides.spring.io/greeting?name=".

Off course, this can be circumvented by using CORS plugin in Chrome but it might be a better solution to actually open the service for public access?

Thanks!

**Comment by dsyer** [comment]
Should be fixed now. (The remote service was re-deployed with `@CrossOrigin("*")`).

**Comment by honzaves** [comment]
Great, thank you!
